### ISSUE TITLE
jmonkeyengine displays "tofu" instead of Japanese font on version 3.2.4-stable-sdk1

### ISSUE THREAD

**Issue by hangingman** [jMonkeyEngine/jmonkeyengine#1380] opened 2020-07-20 10:41 UTC
#### Issue description
- jmonkey engine menu displays what's called "tofu" (small boxes are shown to represent the characters because of there are no characters in the text that cannot be displayed)

#### Steps to reproduce the issue

1.  Go to https://github.com/jMonkeyEngine/sdk/releases/tag/v3.2.4-stable-sdk1
2.  Download jmonkeyplatform-windows-x64.exe and unfold this
3.  Run the jmonkeyengine

#### What's the expected result?
- jmonkey engine shows japanese font correctly

#### What's the actual result?
- jmonkey engine shows many small boxes

#### Additional details / screenshot

- Screen shot

![image](https://user-images.githubusercontent.com/1238507/87929165-f4ee2200-cac0-11ea-97df-96817b173f95.png)

**Comment by pspeed42** [comment] 2020-07-20 10:45
This bug should be filed against the SDK and not the engine.  It's not an engine bug.

**Comment by MeFisto94** [comment] 2020-07-20 10:48
This is a duplicate of https://github.com/jMonkeyEngine/sdk/issues/73
The problem basically is we need a font that supports asian charsets, currently we use `DejaVu Sans Condensed-PLAIN-12` which doesn't.

Try changing the LaF to something netbeans standard, sorry for the inconvenience.
Closing as duplicat of the SDK issue.

**Closed by MeFisto94** 2020-07-20 10:48 UTC
