### ISSUE TITLE
FrameBuffer texture format is hardcoded to BGR8

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#1606] opened 2021-09-14 09:33 UTC
FrameBuffer texture format is hardcoded to BGR8. Apparently this is a bug introduced in 3.4.

This is discussed in:
https://hub.jmonkeyengine.org/t/framebuffer-to-texture-alpha-not-working/44885

I think this requires some investigation. So I created this issue so that this doesn't get forgotten if it is just a thread in the forum.

**Comment by stephengold** [comment] 2021-09-14 12:14
Thanks for opening the issue. I don't fully understand it, but I think it might be related to PR #1400 or PR #1401. I'd appreciate input from @riccardobl .

**Comment by bob0bob** [comment] 2021-09-15 05:05
If you create a Texture with RGBA8  format and assign that to the framebuffer.   using
	      FrameBufferTextureTarget buffTar =  FrameBufferTarget.newTarget((Texture)offTex);
The texture will be marked as BGR8 no matter what the texture is defined to.  It doesn't look at the settings of the texture and use it.
so you have to do the following to get it to support ALpha values.
	      Texture texture = buffTar.getTexture();
	      texture.getImage().setFormat(Format.RGBA8);
Then the Alpha values will be saved.  Otherwise the background where no rendering has taken place will be the background color that is set in the frame buffer.

**Comment by Ali-RS** [comment] 2021-09-15 05:30
>>The texture will be marked as BGR8 no matter what the texture is defined to.

Hm, looking through the code, I could not find where it is reset back to BGR8.

**Comment by riccardobl** [comment] 2021-10-05 20:13
The format is not hardcoded... it might be caused by something else in your code or maybe by the viewPort background

**Comment by stephengold** [comment] 2021-11-20 22:17
I wrote a test app to reproduce the issue, but was not successful:
```java
import com.jme3.app.SimpleApplication;
import com.jme3.texture.FrameBuffer;
import com.jme3.texture.Image;
import com.jme3.texture.Texture2D;

/**
 * Test whether the FrameBuffer texture format is hardcoded to BGR8.
 *
 * @author sgold
 */
public class TestIssue1606 extends SimpleApplication {

    public static void main(String... commandLineArgsIgnored) {
        TestIssue1606 app = new TestIssue1606();
        app.start();
    }

    @Override
    public void simpleInitApp() {
        // Create a Texture with RGBA8 format.
        int width = 256;
        int height = 256;
        Texture2D texture = new Texture2D(width, height, Image.Format.RGBA8);

        // Assign the Texture to a framebuffer.
        FrameBuffer frameBuffer = new FrameBuffer(width, height, 1);
        FrameBuffer.FrameBufferTextureTarget target
                = FrameBuffer.FrameBufferTarget.newTarget(texture);
        frameBuffer.addColorTarget(target);

        // Verify that the target and texture formats are both RGBA8.
        Image.Format targetFmt = target.getFormat();
        assert targetFmt == Image.Format.RGBA8 : targetFmt;
        Image.Format textureFmt = texture.getImage().getFormat();
        assert textureFmt == Image.Format.RGBA8 : textureFmt;
        System.out.println("target: " + targetFmt + ", texture: " + textureFmt);
    }
}
```

The format of the target matches that of the original texture, and the format of the original texture is unchanged.

Until someone provides a complete example that demonstrates the issue, I'll consider this issue invalid.

**Closed** 2021-12-02 22:07 UTC
Labels: invalid
