### ISSUE TITLE
AudioListenerState causes positional audio to fail

### ISSUE THREAD

**Issue by TripleSnail** [jMonkeyEngine/jmonkeyengine#496] opened 2016-05-12 21:13 UTC
I updated my game to jME 3.1 beta 1, and noticed that all my positional sound effects stopped working.
(By 'stopped working' I mean that the sounds are barely recognizable, and often I don't hear them at all)

Then I noticed that when I stop updating the listener location like this (update in a Control):

```
listener.setLocation(localCharacter.getWorldTranslation());
```

then sounds started to work again. Further research led me to call this at simpleInitApp:

```
stateManager.getState(AudioListenerState.class).setEnabled(false);
```

Now all the positional AudioNodes work correctly again, and I can continue with updating the location of the listener.

Should I do something differently, or is there a defect in AudioListenerState?

**Comment by pspeed42** [comment] 2016-05-12 21:56
The audio listener state was added by default.  It was maybe a questionable
decision to do that as it assumes everyone must be using camera position or
whatever.  I guess some apps don't hit this (like mine) because they
already only include the app states they specifically want by passing them
on the super() constructor.  I recommend that in general, by the way.

**Comment by TripleSnail** [comment] 2016-05-13 13:29
I guess it makes sense to update it according to the camera position. I'm okay with both removing it from defaults or leaving it as is, so feel free to close this issue. (Nevertheless, I believe that being explicit is better than implicit)

Thanks for the recommendation. I wasn't aware that there was such super constructor available.

**Comment by ZoltanTheHun** [comment] 2016-07-08 23:27
Hi, this one is a tricky one. I faced the same issue after updating the engine. Thanks for pointing out the rootcause.

**Comment by shadowislord** [comment] 2017-09-15 02:11
This breaks backward compatibility but is expected behavior.. going to close the issue

**Closed by shadowislord** 2017-09-15 02:11 UTC
