### ISSUE TITLE
Wrong light position from .blend

### ISSUE THREAD

**Issue by raphaelbruno** [jMonkeyEngine/jmonkeyengine#521] opened 2016-07-02 03:26 UTC
I have created a .blend and added a Cube and a Light (I tried Point  and Directional Light), I setup light position to (0, 5, 2) and saved the .blend file.

On JME3:
Right click .blend file "Convert to j3o Binary", Double click .j3o(or .blend file), it generate a empty node with position (0, 5, 2) and a light on position (0, 0, 0). On render the light bright from position (0, 0, 0).

Scene
&nbsp;&nbsp;&nbsp;&nbsp;|-- Point [Node(0, 5, 2)]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- LightControl [Property Light is Empty]
&nbsp;&nbsp;&nbsp;&nbsp;|-- Cube
&nbsp;&nbsp;&nbsp;&nbsp;|-- PointLight [PointLight(0, 0, 0)]

Is it a bug or I am making something wrong?

**Environment:**
**Product Version:** jMonkeyEngine SDK 3.1.0-beta1-SNAPSHOT
**Java:** 1.8.0_77; Java HotSpot(TM) 64-Bit
**System:** Elementary OS 0.3.2 Freya [Ubuntu based](Linux version 3.19.0-64-generic running on amd64)

**Comment by davidB** [comment] 2016-07-02 06:56
It's the expected behavior. To the same behavior than with in blender, in JME you should have : 
* 1 PointLight attached to root, that define what should be enlighted : children Spatial of root
* Point [Node(0, 5, 2)] + LightControl that set the position of PointLight to the position of Point (every frame).

**Comment by raphaelbruno** [comment] 2016-07-02 11:21
Ok, so, what i do to light to bright on (0, 5, 2) and not on (0, 0, 0)?

I seen on LightControl, PointLight property is set as empty, is it normal?

**Comment by MeFisto94** [comment] 2016-07-02 13:30
The LightControl should set the Position to follow the Node(0, 5, 2).
The reason for this behavior is, that a Light only enlightens what is under it's tree and as such it wouldn't light the whole scene when added to a node.

**Comment by shadowislord** [comment] 2017-09-15 02:11
Seems like expected behavior, so I am closing the issue

**Closed by shadowislord** 2017-09-15 02:11 UTC
