### ISSUE TITLE
Inconsistency detected by ld.so: dl-lookup.c: 111

### ISSUE THREAD

**Issue by HiranChaudhuri** [jMonkeyEngine/jmonkeyengine#1887] opened 2022-12-31 10:59 UTC
I just downloaded the latest release 3.5.2-stable, unpacked the zip and ran it on my Ubuntu 20.04 system.
On startup a window appeared asking to to choose the test, and I picked TestJoystick.
Then a window asking for display settings appeared, in which I just clicked Continue.
After that I am back to the console with the below output.

```
$ ./jMonkeyEngine3.jar 
Dec 31, 2022 11:54:57 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.5.2-stable
 * Branch: HEAD
 * Git Hash: 8ab3d24
 * Build Date: 2022-04-21
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
$
```

Is this an issue with my installation, or is it with JME? What could I look at to get further information?

**Comment by pspeed42** [comment] 2022-12-31 11:05
You should ask trouble shooting questions like this on the JME forum:
https://hub.jmonkeyengine.org/

More people will see it there.  You can also include more information, like did you run any of the other tests or did you just randomly start with TestJoyStick and so that's the one you say is broken?

**Comment by MeFisto94** [comment] 2022-12-31 11:43
This definitely is an issue, but not with the joysticks only, it's because lwjgl2 doesn't play nicely with your openJDK version.
#1247 

@pspeed42 This is the lwjgl2 problem I was talking about, do you have an updated version of lwjgl2 that we could ship?

**Comment by Ali-RS** [comment] 2023-01-04 06:03
@HiranChaudhuri as a quick solution, you may use the Adoptium OpenJDK 12+

**Comment by Ali-RS** [comment] 2023-01-05 06:25
@HiranChaudhuri which java version are you using?
I am trying to reproduce it on my Linux Mint. I tested with Oracle JDK 11.0.5 but I could not reproduce it.

**Comment by HiranChaudhuri** [comment] 2023-01-07 11:31
> You should ask trouble shooting questions like this on the JME forum: https://hub.jmonkeyengine.org/
> 
> More people will see it there. You can also include more information, like did you run any of the other tests or did you just randomly start with TestJoyStick and so that's the one you say is broken?

I started and picked the TestJoyStick (since I was interested in joystick handling) and thus I claim that one does not work.
Now I tried TestFog, but it fails as well. The suspect that Joystick is not the only one is correct.

**Comment by HiranChaudhuri** [comment] 2023-01-07 11:49
> This definitely is an issue, but not with the joysticks only, it's because lwjgl2 doesn't play nicely with your openJDK version. #1247
> 
> @pspeed42 This is the lwjgl2 problem I was talking about, do you have an updated version of lwjgl2 that we could ship?

That may be. To be honest, i just launched the process like
`./jMonkeyEngine3.jar`
and thus did not choose any JDK, and did not even think of that. So now I am trying to find out what exactly is running under the hood...

Apparently my command line got translated into this (this is found on the process list):
`java -Djava.library.path=/usr/lib/jni:/usr/lib/alpha-linux-gnu/jni:/usr/lib/x86_64-linux-gnu/jni:/usr/lib/aarch64-linux-gnu/jni:/usr/lib/x86_64-kfreebsd-gnu/jni:/usr/lib/powerpc64-linux-gnu/jni:/usr/lib/powerpc64le-linux-gnu/jni:/usr/lib/s390x-linux-gnu/jni:/usr/lib/sparc64-linux-gnu/jni -jar /.../jMonkeyEngine3.jar`

But when I investigate
`/proc/<pid>/exe -> /usr/lib/jvm/java-16-openjdk-amd64/bin/java`

So it seems I was trying to run on OpenJDK 16, likely the same I get when executing java directly:

```
$ java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)
$

As I also have OpenJDK 11 installed I tried running 
`/usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar jMonkeyEngine3.jar`
but the results were the same.
Now I installed OpenJDK 17 (the latest available on the Ubuntu 20 repos) and am still getting the same results.
```

**Comment by HiranChaudhuri** [comment] 2023-01-07 11:56
> I could reproduce it with ubuntu jre 11.0.9.1 and confirmed that using lwjgl 2.9.4 build from @MeFisto94 the issue goes away.

So how can I fix this? How would I install this lwjgl, or should it be part of the jMonkeyEngine3 package that I downloaded? After all it contains liblwjgl64.so and libopenal64.so. But I am not sure whether they would get used at runtime.

**Comment by Ali-RS** [comment] 2023-01-07 12:37
I am working on this issue and hope we fix it in the next release. But if you want to give it a try,  download the [liblwjgl64.so.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/10366253/liblwjgl64.so.zip) and extract the zip file, and copy the `liblwjgl64.so` into the `lwjgl-platform-natives-linux.jar` file which is inside `lib` directory.

**Comment by Ali-RS** [comment] 2023-01-07 13:32
Thanks for trying it out and reporting the result.

>but display a windows saying that no joystick was found.
Despite I believe I have one attached. But this may be a different issue.

Yes, I belive that is a different issue.

**Comment by Ali-RS** [comment] 2023-01-11 08:54
Fixed in https://github.com/jMonkeyEngine/jmonkeyengine/commit/3e1b823bdb7c7a2e60916dab32186141b3fd9800

**Closed by Ali-RS** 2023-01-11 08:54 UTC
Labels: duplicate
