### ISSUE TITLE
No AnimControl when loading Oto model since JME 3.3.0

### ISSUE THREAD

**Issue by rkraneis** [jMonkeyEngine/jmonkeyengine#1375] opened 2020-05-31 20:38 UTC
Walking through the [Hello Animation tutorial](https://wiki.jmonkeyengine.org/jme3/beginner/hello_animation.html) I stumbled over the fact that many `animation` classes are now deprecated and that the actual tutorial code is throwing an NPE when trying to add a listener to the `control` which should have been added by `assetManager`:
```
player = (Node) assetManager.loadModel("Models/Oto/Oto.mesh.xml");
// ...
control = player.getControl(AnimControl.class);
control.addListener(this); // NPE
```
Is this workflow not supported anymore at all? What would the _new_ way of doing the tutorial?

(The tutorial still worked as is with JME 3.2.4-stable)

**Comment by pspeed42** [comment] 2020-05-31 20:51
You will get more response by asking trouble shooting questions on the forum.

**Comment by rkraneis** [comment] 2020-05-31 20:55
I _believe_ this is a bug. Switching the model out for Jaime (as in TestJaime) or OtoOldAnim.j3o makes the code work. So something must happened to animations in Ogre meshes ...

**Comment by pspeed42** [comment] 2020-05-31 21:04
There is a new animation system.  If you want to report a bug with the tutorial... here is the place.  The bug will sit here until the 3-4 people who read the issues will see it.

If you want to actually figure out how to get past the problem as quickly as possible... the forum is the place.

**Comment by rkraneis** [comment] 2020-05-31 21:07
Ah, yes, it's more about reporting the bug and hinting that the tutorial might need an update ;-) If I can't figure out what to do I'll definitely hop over to the forums :+1:

**Comment by Ali-RS** [comment] 2020-06-01 05:13
Hmm... did not know Nehon had updated the Ogre loader to use the new animation system (I thought only Gltf loader does). Good.

**Comment by rkraneis** [comment] 2020-06-01 08:33
Hmm, I have the tutorial code now updated in a quite straight forward manner (similar to what @stephengold did in TestBoneRagdoll). I guess creating a PR against the wiki might be a good “first issue” getting my feet wet?

**Comment by pspeed42** [comment] 2020-06-01 08:35
Definitely.

**Comment by stephengold** [comment] 2020-06-01 23:47
Note that the wiki tutorial code is (approximately) duplicated in jme3-examples: https://github.com/jMonkeyEngine/jmonkeyengine/tree/master/jme3-examples/src/main/java/jme3test/helloworld

**Comment by rkraneis** [comment] 2020-06-05 16:53
Thanks @stephengold, I checked out TestOgreAnim and TestOgreAnimComplex. Will ask a few questions in the forums :)

**Comment by stephengold** [comment] 2021-03-24 17:37
Closing this as a duplicate of #1402 (even though this was filed first!)

**Closed by stephengold** 2021-03-24 17:37 UTC
Labels: Documentation
