### ISSUE TITLE
jme3-bullet-native and java 9+

### ISSUE THREAD

**Issue by TalosDx** [jMonkeyEngine/jmonkeyengine#977] opened 2018-12-17 22:38 UTC
When i tried launch the project with jme3, i have this error: 
Caused by: java.lang.module.FindException: Automatic-Module-Name: native: Invalid module name: 'native' is not a Java identifier
Solution: 
https://stackoverflow.com/questions/46501388/unable-to-derive-module-descriptor-for-auto-generated-module-names-in-java-9

Please tell me how to solve this problem? Just plug in the module directly? Or maybe the problem is not only for me?

build.gradle
https://pastebin.com/P3Y5KRP0

**Comment by Ali-RS** [comment] 2018-12-18 04:31
JME not support module system at the moment. You should add sourceCompatibility = 1.8 in your project if you want to use java 9 onward. 
If you wish you can go ahead and make a pr to support module system on JME.

**Comment by TalosDx** [comment] 2018-12-18 22:03
I do not write my project as a module and the only way to use javafx 11 and gradle is to use javafx 11 modules, but when using them java crashes the program saying that the word 'native' is already reserved and cannot be used in the jar file name.
Just change 'jme3.bullet.native' to something else, for example 'jme3.bullet.app', then java works as it should and builds the project correctly.

**Comment by tlf30** [comment] 2019-03-17 17:26
I have personally not looked into this very much yet, but I feel like this is an issue is not just in JME, I have seen other libraries with similar issues. 

The problem is that renaming a jar file of a core library will break backwards compatibility. In my opinion, this needs to be fixed in Java, not JME.

**Comment by empirephoenix** [comment] 2019-03-18 06:14
..Wait why does this work for me? I use java11 and the native bullet and have not the same issue?

**Comment by TalosDx** [comment] 2019-03-18 09:11
Try use javafx on your project or any module.

**Comment by empirephoenix** [comment] 2019-03-18 09:37
Um, I do, so either eclipse does something clever in the run config, I don't know about, or there is some way this can be setup. 

https://pastebin.com/bUZjdHYA

**Comment by tlf30** [comment] 2019-03-19 00:42
So I just updated one of my jme apps which uses native bullet to jdk 11, and loaded up a javafx ui on it. I have had no issues (except for a couple annoying illegal access notifications).

**Comment by TalosDx** [comment] 2019-03-19 04:41
Show build.gradle

**Comment by tlf30** [comment] 2019-03-19 05:24
I'm using maven

**Comment by TalosDx** [comment] 2019-03-19 05:26
Then show pom.xml

**Comment by tlf30** [comment] 2019-03-19 15:41
Sorry, I was not at a computer. I cannot show the entire pom, it has come company info in it, but here are the relevant parts:
```
    <properties>
        <jme3_g>org.jmonkeyengine</jme3_g>
        <jme3_v>3.3.0-SNAPSHOT</jme3_v>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <dependencies>
        <!-- JME 3 Stuff -->
        <dependency>
            <groupId>${jme3_g}</groupId>
            <artifactId>jme3-core</artifactId>
            <version>${jme3_v}</version>
        </dependency>
        <dependency>
            <groupId>${jme3_g}</groupId>
            <artifactId>jme3-networking</artifactId>
            <version>${jme3_v}</version>
        </dependency>
        <dependency>
            <groupId>${jme3_g}</groupId>
            <artifactId>jme3-bullet-native</artifactId>
            <version>${jme3_v}</version>
        </dependency>
        <dependency>
            <groupId>${jme3_g}</groupId>
            <artifactId>jme3-bullet</artifactId>
            <version>${jme3_v}</version>
        </dependency>
        <dependency>
            <groupId>${jme3_g}</groupId>
            <artifactId>jme3-desktop</artifactId>
            <version>${jme3_v}</version>
        </dependency>
        <dependency>
            <groupId>${jme3_g}</groupId>
            <artifactId>jme3-lwjgl</artifactId>
            <version>${jme3_v}</version>
        </dependency>
        <dependency>
            <groupId>${jme3_g}</groupId>
            <artifactId>jme3-niftygui</artifactId>
            <version>${jme3_v}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.simsilica/lemur -->
        <dependency>
            <groupId>com.simsilica</groupId>
            <artifactId>lemur</artifactId>
            <version>1.10.1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.simsilica/lemur-proto -->
        <dependency>
            <groupId>com.simsilica</groupId>
            <artifactId>lemur-proto</artifactId>
            <version>1.9.1</version>
        </dependency>
        <dependency>
            <groupId>com.simsilica</groupId>
            <artifactId>lemur-props</artifactId>
            <version>1.0.1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>27.0.1-jre</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all -->
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.5.6</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
            <type>jar</type>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-configuration2 -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-configuration2</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
            <version>1.9.3</version>
        </dependency>
        <!-- Java FX JME3 UI -->
        <dependency>
            <groupId>com.jme3</groupId>
            <artifactId>jfx</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>11.0.2</version>
        </dependency>
    </dependencies>
    
    <repositories>
        <repository>
            <id>jcenter</id>
            <url>http://jcenter.bintray.com</url>
        </repository>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-javasabr-maven</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/javasabr/maven</url>
        </repository>
    </repositories>
    
    <build>
        <resources>
            <resource>
                <directory>src/main/resources/assets</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <release>11</release>
                    <compilerArgs>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <addDefaultImplementationEntries>
                                true
                            </addDefaultImplementationEntries>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
I'm not doing anything special in it. I am using JavaFX11 with OpenJDK11. Bullet loads and works fine.

**Comment by tlf30** [comment] 2019-04-12 15:06
@TalosDx I can we close this when we merge in #1059?
Also, in all my work with JDK11 with JME3, I still have yet to replicate the invalid module name error, can you please test the JME3-JDK11 branch and see if you still get the error.

**Comment by tlf30** [comment] 2019-07-02 16:43
@TalosDx has your issue been resolved with master? I still have been unable to replicate your issue.

**Comment by TalosDx** [comment] 2019-07-09 15:24
I will try this weekend, I hope everything will be fine

**Comment by stephengold** [comment] 2020-02-19 00:35
Any updates on this issue?

**Comment by stephengold** [comment] 2021-03-15 14:17
Closed as irreproducible.

**Closed by stephengold** 2021-03-15 14:17 UTC
