### ISSUE TITLE
Using jogl and Offscreen leads to "No OpenGL context current on this thread" error

### ISSUE THREAD

**Issue by davidbilge** [jMonkeyEngine/jmonkeyengine#490] opened 2016-04-29 06:42 UTC
When starting my App with `Type.OffscreenSurface` and a `JOGL_` renderer, I get a `No OpenGL context current on this thread` error.

The problem seems to be that `JoglOffscreenBuffer` calls `GLContext.getCurrentGL()` in a new Thread and there is no `GLContext` attached to that thread.

This applies to 3.1.0-beta1.

**Comment by gouessej** [comment] 2016-04-29 08:40
Hi. Please provide a SSCCE: http:sscce.org I'm going to look at the source code.

**Comment by gouessej** [comment] 2016-04-29 08:52
The problem is probably here: https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-jogl/src/main/java/com/jme3/system/jogl/JoglOffscreenBuffer.java#L64 It just stupidly mimics the way another similar API is used. There is no current OpenGL context here. I can fix this bug when I'm at home in a few hours. You can comment those lines and rebuild JMonkeyEngine in the meantime.

**Comment by gouessej** [comment] 2016-04-29 08:58
Actually, those lines are useless as JOGL can create an offscreen buffer even with no full FBO support. I have to add those lines too but it doesn't concern your bug: if (settings.getRenderer().equals(AppSettings.JOGL_OPENGL_FORWARD_COMPATIBLE)) {
        	caps = new GLCapabilities(GLProfile.getMaxProgrammable(true));
        } else {
        	caps = new GLCapabilities(GLProfile.getMaxFixedFunc(true));
        }

I'll fix it in about 11 hours, sorry for the delay.

**Comment by davidbilge** [comment] 2016-04-29 09:09
I made some modifications too: https://gist.github.com/davidbilge/d19f5fbcc5650ba4432ecf30467c5047

**Comment by gouessej** [comment] 2016-04-29 11:41
Your modifications are wrong. At first, making the OpenGL context current in this method isn't

**Comment by davidbilge** [comment] 2016-04-29 11:55
Yeah, about setting the renderer: I had to do that because I use my "CustomJoglOffscreenBuffer" by configuring a `CUSTOM`renderer in my `AppSettings` - and if I do that, `JoglContext` complains about an "unsupported renderer" in line 189. This is really just a workaround to get my custom implementation to work.

If I don't make the `GLContext` current, I get this Exception:

    Exception in thread "jME3 Main" java.lang.NullPointerException
    	at com.jme3.system.jogl.JoglContext.initContextFirstTime(JoglContext.java:157)
    	at com.jme3.system.jogl.JoglContext.internalCreate(JoglContext.java:221)
    	at com.example.jmonkeytest.CustomJoglOffscreenBuffer.initInThread(CustomJoglOffscreenBuffer.java:59)
    	at com.example.jmonkeytest.CustomJoglOffscreenBuffer.run(CustomJoglOffscreenBuffer.java:100)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by gouessej** [comment] 2016-04-29 14:27
Ok thank you for your detailed explanations. Please be very accurate on what you are trying to do. You would have had a similar concern with the other available backends. Please rather use something like "JOGLCustom" instead of "CUSTOM" and it will work. I'll fix the null dereference too, it might require much time than I thought.

**Comment by davidbilge** [comment] 2016-04-29 14:49
In `JmeDesktopSystem#284` the custom renderer name is expected to start with "CUSTOM", hence the choice. To be precise, I used `settings.setRenderer("CUSTOMcom.example.jmonkeytest.CustomJoglOffscreenBuffer");`.

**Comment by gouessej** [comment] 2016-04-30 08:47
Yes but actually you can't use a custom renderer without creating your own JMonkeyEngine context and none of the implementation of JmeContext are designed to be extended, which explains why you obtained an UnsupportedOperationException. In my humble opinion, there are two bugs to fix. At first, please check whether creating an offscreen renderer with the JOGL backend works as is (which is probably not the case). Then, I'll do my best to fix your specific use case with a custom offscreen buffer but it will only work with the JOGL backend (which is ok for me as a JogAmp maintainer officially responsible for engine support).

**Comment by davidbilge** [comment] 2016-04-30 11:20
Thank you for you effort. I do not actually want to use a custom offscreen buffer. I only did that in this case to be able to pinpoint the bugs in the official implementation. As soon as they are fixed I can easily use the standard way. 

Using offscreen mode does not work with the jogl backend as of now—it does if the fixes from my custom version are applied, though.

**Comment by gouessej** [comment] 2016-04-30 11:51
You're welcome. This feature is already working in JogAmp's Ardor3D Continuation, I'll try to do something similar in JMonkeyEngine.

**Comment by gouessej** [comment] 2016-04-30 11:57
I will modify the classes extending JoglContext so that they use the GLContext of the drawable when it is possible and I will remove the useless tests.

**Comment by gouessej** [comment] 2016-05-18 19:16
Please let me know whether it works. I'm not sure that I should release the OpenGL context. The other offscreen canvases that I implemented do something similar to what you did when they use a pbuffer but the most reliable one simply uses a NEWT offscreen GLWindow and is a lot cleaner.

**Comment by shadowislord** [comment] 2017-09-15 02:13
The fix has already been committed, going to close the issue

**Closed by shadowislord** 2017-09-15 02:13 UTC

**Comment by GitHub-Ronald** [comment] 2019-05-21 09:05
Still have this problem. at (JoglContext.java:347)

**Comment by gouessej** [comment] 2019-05-21 15:55
@GitHub-Ronald Please post the full stack trace on the official JogAmp forum as I'm very rarely here on Github.

**Comment by gouessej** [comment] 2019-05-21 16:00
@GitHub-Ronald getNumSamplesToUse() must be called on the thread on which the OpenGL context is current, otherwise you'll get a NullPointerException.
