### ISSUE TITLE
Display.getPixelScaleFactor() doesn't exists anymore

### ISSUE THREAD

**Issue by blackorbit1** [jMonkeyEngine/jmonkeyengine#1987] opened 2023-03-14 20:45 UTC
Hello, it looks like the method `getPixelScaleFactor()` doesn't exists anymore in the class `Display`.
https://github.com/jMonkeyEngine/jmonkeyengine/blob/44a50de4d7797dc3dd8d46cd1f51308e9a05d627/jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java#L116

I was trying to test the [JME3 Canvas in a Swing GUI](https://wiki.jmonkeyengine.org/docs/3.4/tutorials/how-to/java/swing_canvas.html) demo and had this exception raised : 
![image](https://user-images.githubusercontent.com/38140797/225131671-758220bc-ca76-4c56-bcc4-dd120247a27e.png)

I tried to switch between `org.jmonkeyengine:jme3-lwjgl3` and `org.jmonkeyengine:jme3-lwjgl` in `3.5.2-stable` version but got the same issue.

**Comment by pspeed42** [comment] 2023-03-14 21:28
You should post trouble-shooting questions to the forum where more people will see it.

It seems you have version mismatches in your dependencies.  Do note that none of the Swing/AWT stuff will work properly with lwjgl3... but the error seems unrelated to that as it's not even involving the swing stuff yet.  Folks on the forum may provide better support.

**Comment by tonihele** [comment] 2023-03-15 08:08
Display class is specific to LWJGL 2 I might add too.

**Comment by pspeed42** [comment] 2023-03-15 15:32
Yeah, that's why I suggested this is caused by a dependency mismatch in OP's build.  It's just a guess but I can't explain the errors otherwise.

**Comment by Ali-RS** [comment] 2023-03-15 15:58
>it looks like the method getPixelScaleFactor() doesn't exists anymore in the class Display.

The `getPixelScaleFactor` method is still there:

https://github.com/LWJGL/lwjgl/blob/2df01dd762e20ca0871edb75daf670ccacc89b60/src/java/org/lwjgl/opengl/Display.java#L1372-L1375

I tried [TestCanvas.java](https://github.com/jMonkeyEngine/jmonkeyengine/blob/c7a734d59023c8b6726bfa55272f7fbc349ea760/jme3-examples/src/main/java/jme3test/awt/TestCanvas.java) from master and 3.5.2-stable and it works fine for me with lwjgl2.

As Paul said, it should be a dependency mismatch. @blackorbit1 please recheck if you have the lwjgl2 dependency.

I am closing this. If you still had the issue please feel free to ask it on the JME forum and show us what your `build.grade` file looks like and possibly provide us a minimal test case so we can reproduce the issue.

**Closed by Ali-RS** 2023-03-15 15:58 UTC
