### ISSUE TITLE
v3.6 crashes attempting to run example apps in fullscreen with LWJGL v2

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1890] opened 2023-01-03 19:14 UTC
Investigating a possible regression in JME v3.6.0-alpha1, I tried to run some of the apps in jme3-examples in fullscreen mode ... for example `jme3test.helloworld.HelloJME3` (though I ran into identical behavior with other example apps). Here's what happens:

+ The display settings dialog appears with "Fullscreen" not checked and "Refresh Rate" blank.
+ I check the box for "Fullscreen".
+ The "Screen Resolution" changes to1920x1080 and the "Refresh Rate" changes to 55 Hz. Unfortunately, 55 Hz isn't a valid refresh rate for my display adapter. I believe the valid rates are 24, 30, and 60 Hz.
+ When I try to select a different refresh rate, there are only 6 available options: 50 Hz, 51 Hz, 52 Hz, 53 Hz, 54 Hz, and 55 Hz. None of these are valid rates.
+ After I click the "Continue" button, I get two "Error in Application" dialogs and the app crashes.

The console output is:
```console
Jan 03, 2023 10:59:04 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.6.0-alpha1
 * Branch: master
 * Git Hash: 5b9fc87
 * Build Date: 2023-01-03
Jan 03, 2023 10:59:05 AM com.jme3.app.LegacyApplication handleError
SEVERE: Failed to create display
java.lang.RuntimeException: Unable to find fullscreen display mode matching settings
	at com.jme3.system.lwjgl.LwjglDisplay.createContext(LwjglDisplay.java:80)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:120)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:221)
	at java.base/java.lang.Thread.run(Thread.java:833)

Jan 03, 2023 10:59:05 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.IllegalMonitorStateException: current thread is not owner
	at java.base/java.lang.Object.notifyAll(Native Method)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:135)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:221)
	at java.base/java.lang.Thread.run(Thread.java:833)


Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "jME3 Main"
```

Excerpt from glxinfo (to document my graphics configuration):
```console
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 545/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 390.157
OpenGL core profile shading language version string: 4.60 NVIDIA
```

This was with "jme3-lwjgl" (LWJGL v2, which is currently the default jme3-examples build). Here's what happened when I switched the build to use "jme3-lwjgl3" (LWJGL v3):

+ The display settings dialog appears with "Fullscreen" not checked and "Refresh Rate" blank.
+ I check the box for "Fullscreen".
+ The "Screen Resolution" changes to1920x1080 and the "Refresh Rate" changes to 55 Hz.
+ When I try to select a different refresh rate, there are only 6 available options: 50 Hz, 51 Hz, 52 Hz, 53 Hz, 54 Hz, and 55 Hz.
+ After I click the "Continue" button, the application runs fullscreen.

**Comment by Ali-RS** [comment] 2023-01-03 21:14
Sounds this is a duplicate of https://github.com/jMonkeyEngine/jmonkeyengine/issues/947

**Comment by stephengold** [comment] 2023-01-03 22:45
ertugrulcetin's solution doesn't work for me.

1280x960 screen resolution *does* work for me.

I think we can close this as a duplicate of #947.

**Comment by Ali-RS** [comment] 2023-01-04 07:59
@stephengold do you have a secondary monitor connected?

**Comment by stephengold** [comment] 2023-01-04 16:39
only one monitor in my setup

**Comment by Ali-RS** [comment] 2023-01-04 16:47
Can you please run this Linux command  `xrandr -q` and share the result?

**Comment by Ali-RS** [comment] 2023-01-04 17:18
@stephengold  can you test with this lwjgl jar and see if it fixes your issue?
 [lwjgl.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/10346060/lwjgl.zip)

I have forked lwjgl2 and applied this [patch](https://hub.jmonkeyengine.org/t/fix-for-unable-to-find-fullscreen-display-mode-matching-settings-for-multimonitor-configurations-in-linux/41510) provided by @riccardobl

**Comment by stephengold** [comment] 2023-01-05 18:12
>  can you please test with this lwjgl jar and see if it fixes your issue?

1. I unzipped the ZIP you suggested and moved the JAR to "lib/lwjgl.jar" .
2. I edited jme3-lwjgl/build.gradle to change
```groovy
api 'org.lwjgl.lwjgl:lwjgl:2.9.3'
```
to
```groovy
api 'lwjgl:lwjgl'
```

3. When I tried to run HelloJme3, I got:
```console
an 05, 2023 9:28:30 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.6.0-alpha1
 * Branch: master
 * Git Hash: 5b9fc87
 * Build Date: 2023-01-05
Exception in thread "jME3 Main" java.lang.UnsatisfiedLinkError: The required native library 'openal64' was not found in the classpath via 'native/linux/libopenal64.so'. Error message: no openal64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at com.jme3.system.NativeLibraryLoader.loadNativeLibrary(NativeLibraryLoader.java:590)
	at com.jme3.system.lwjgl.LwjglContext.loadNatives(LwjglContext.java:229)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:219)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

4. I added
```groovy
runtimeOnly 'org.lwjgl.lwjgl:lwjgl-platform:2.9.3:natives-linux'
```

(Are those the correct natives to use with your fork?)

5. When I ran `HelloJME3` I still got invalid refresh rates and
```console
Jan 05, 2023 10:05:06 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.6.0-alpha1
 * Branch: master
 * Git Hash: 5b9fc87
 * Build Date: 2023-01-05
Jan 05, 2023 10:05:06 AM com.jme3.app.LegacyApplication handleError
SEVERE: Failed to create display
java.lang.RuntimeException: Unable to find fullscreen display mode matching settings
	at com.jme3.system.lwjgl.LwjglDisplay.createContext(LwjglDisplay.java:80)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:120)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:221)
	at java.base/java.lang.Thread.run(Thread.java:833)

Jan 05, 2023 10:05:06 AM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.IllegalMonitorStateException: current thread is not owner
	at java.base/java.lang.Object.notifyAll(Native Method)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:135)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:221)
	at java.base/java.lang.Thread.run(Thread.java:833)


Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "jME3 Main"
```

**Comment by stephengold** [comment] 2023-01-05 19:18
Both LWJGLv2 and LWJGLv3 provide methods to enumerate the available display modes. For my Acorus library, I wrote utility methods to dynamically determine which version(s) of LWJGL are available and invoke the appropriate method. It seems to work reliably.

I think we should do something similar for the v3.6 display-settings dialog.

**Comment by pspeed42** [comment] 2023-01-05 19:38
Yes, I agree... it seems to be something we've been missing for a long time to be able to generically get a list of "GL library supported modes" without guessing by asking AWT.

**Comment by Ali-RS** [comment] 2023-01-05 19:40
Good idea!

**Comment by stephengold** [comment] 2023-01-05 22:00
I still think this is a duplicate of #947. Not sure why it got re-opened.

**Comment by Ali-RS** [comment] 2023-01-05 22:06
Well, I believe the causes are different and need different treatments.
 One is related to the AWT issue (yours) and one is that lwjgl2 takes the first display in the map as the primary display which is not always true. They both produces same exceptions.

**Comment by Ali-RS** [comment] 2023-01-08 10:01
Replacing these lines 

https://github.com/jMonkeyEngine/jmonkeyengine/blob/9e54d443f50dff600c5561f546a18031a754a580/jme3-awt-dialogs/src/main/java/com/jme3/awt/AWTSettingsDialog.java#L246-L248

with

```
modes = DsUtils.listDisplayModes().toArray(new DisplayMode[0]);

```

I get this error at runtime

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:843)
	at java.lang.System.loadLibrary(System.java:1136)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.jme3.util.DsUtils.<clinit>(DsUtils.java:92)
	at com.jme3.awt.AWTSettingsDialog.<init>(AWTSettingsDialog.java:247)
	at com.jme3.awt.AWTSettingsDialog$1.run(AWTSettingsDialog.java:162)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

**Comment by Ali-RS** [comment] 2023-01-08 13:20
Calling `DsUtils.listDisplayModes()` after the app starts works fine but if I call it before the app starts it gives the above error.

**Comment by stephengold** [comment] 2023-01-08 17:31
Could you load the natives explicitly, before the app starts?

**Comment by Ali-RS** [comment] 2023-01-08 17:45
With lwjgl3 it returns an empty array.

>Could you load the natives explicitly, before the app starts?

In the case of lwjgl2 if I add `NativeLibraryLoader.loadNativeLibrary("lwjgl", false);` before the app starts and before calling to `DsUtils.listDisplayModes()` it works fine and the crash goes away.

But with lwjgl3 if load natives (`NativeLibraryLoader.loadNativeLibrary("lwjgl3", false);`,  `NativeLibraryLoader.loadNativeLibrary("glfw-lwjgl3", false);`) before app starts and before calling to `DsUtils.listDisplayModes()` it does not make any difference and still returns an empty array.


I made a test case

```

import com.jme3.app.SimpleApplication;
import com.jme3.awt.AWTSettingsDialog;
import com.jme3.system.NativeLibraryLoader;
import com.jme3.util.DsUtils;

import java.awt.*;
import java.util.Arrays;

/**
 * @author Ali-RS
 */
public class TestDsUtils extends SimpleApplication {

    public static void main(String[] args) {
        // Load Natives For LWJGL 2
        NativeLibraryLoader.loadNativeLibrary("lwjgl", false);

        // Load Natives For LWJGL 3
        NativeLibraryLoader.loadNativeLibrary("lwjgl3", false);
        NativeLibraryLoader.loadNativeLibrary("glfw-lwjgl3", false);

        System.out.println("Debugging Display Modes Before Start");
        debugDisplayModes(); // Does not work with LWJGL 3

        TestDsUtils app = new TestDsUtils();
        app.setShowSettings(false);
        app.start();

        System.out.println("Debugging Display Modes After Start");
        debugDisplayModes(); // Does not work with LWJGL 3
    }

    private static void debugDisplayModes() {
        DisplayMode[] modes = DsUtils.listDisplayModes().toArray(new DisplayMode[0]);//device.getDisplayModes();
        Arrays.sort(modes, new AWTSettingsDialog.DisplayModeSorter());

        System.out.println("Num Modes:" + modes.length);
        for (DisplayMode mode : modes) {
            System.out.println("Size=[" + mode.getWidth() + "," + mode.getHeight() + "], refreshRate=" + mode.getRefreshRate() );
        }
    }

    @Override
    public void simpleInitApp() {
        System.out.println("Debugging Display Modes From simpleInitApp");
        debugDisplayModes();
    }
}


```

**Comment by stephengold** [comment] 2023-01-08 18:24
LWJGL v3 loads its natives using a static initializer, so there's no need for us to explicitly load them. I suspect the test app fails with LWJGL v3 because `GLFW.glfwInit()` isn't invoked prior to `DsUtils.listDisplayModes()`.

**Comment by Ali-RS** [comment] 2023-01-08 18:45
>I suspect the test app fails with LWJGL v3 because GLFW.glfwInit() isn't invoked prior to DsUtils.listDisplayModes().

You were right, if I call `GLFW.glfwInit();` before DsUtils.listDisplayModes() then it works fine. But I doubt if this might have any breaking effect?

**Comment by stephengold** [comment] 2023-01-08 19:01
The cleanest solution, I think, would be to have 2 different settings dialogs: one for LWJGL v2 and one for LWJGL v3.

The one for LWJGL v2 could use AWT to create the dialog, but it would use `org.lwjgl.opengl.Display.getAvailableDisplayModes()` to enumerate display modes. That would address this issue.

The one for LWJGL v3 wouldn't use AWT at all.

**Comment by stephengold** [comment] 2023-01-08 20:21
>  I doubt that this has a breaking effect.

There is a small amount of configuration that must occur prior to `GLFW.glfwInit()`, such as configuring GLFW debugging and "glfw_async". These would have to be configured using config files, environment variables, command-line arguments, etcetera instead of the settings dialog and `AppSettings`.

Or are you concerned about the possibility that `glfwInit()` might get invoked twice?

**Comment by Ali-RS** [comment] 2023-01-09 06:52
>Or are you concerned about the possibility that glfwInit() might get invoked twice?

Yes, this was one of the concerns. But seems calling it multiple times does not cause an issue, at least in my case.

The next concern is that `glfwInit()` must be called before doing anything with AWT. (I remember I have seen this mentioned somewhere by @Spasi)

So in the case of the `TestChooser` app it must be inside the main and in the case of `AwtSettingsDialog`, it must be before calling to this:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/00a859709032c192f3b48f5c596124cbaf883aca/jme3-awt-dialogs/src/main/java/com/jme3/system/JmeDialogsFactoryImpl.java#L41


otherwise, it crashes the app in my case with this error:

```
X Error of failed request:  RenderBadPicture (invalid Picture parameter)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  7 (RenderFreePicture)
  Picture id in failed request: 0x4000024
  Serial number of failed request:  1452
  Current serial number in output stream:  1458
```

and 

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fce4acf3fc4, pid=11844, tid=0x00007fce2056c700
#
# JRE version: OpenJDK Runtime Environment (8.0_352-b08) (build 1.8.0_352-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.352-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpthread.so.0+0xbfc4]  pthread_mutex_lock+0x4
#
```

I created `DsUtils.initNatives()`, I call it in TestChooser.main and JmeDialogsFactoryImpl.showSettingsDialog()

```
    /**
     * Call this only when app has not started yet (e.g. when requesting
     * display modes from settings dialog).
     */
    public static void initNatives() {
        if (initializedNatives) {
            return;
        }
        
        if (hasLwjglVersion3()) {
            try {
                Class<?> glfwClass = Class.forName("org.lwjgl.glfw.GLFW");
                Method glfwInit = glfwClass.getDeclaredMethod("glfwInit");
                glfwInit.invoke(null);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException |
                     IllegalAccessException exception) {
                throw new RuntimeException(exception);
            }
        } else if (hasLwjglVersion2()) {
            NativeLibraryLoader.loadNativeLibrary("lwjgl", true);
        }

        initializedNatives = true;
    }
```

**Comment by Ali-RS** [comment] 2023-01-09 07:52
>The cleanest solution, I think, would be to have 2 different settings dialogs: one for LWJGL v2 and one for LWJGL v3.

Agree with you.

By the way, a simple trick also could be to just ignore the "refresh rate" in `me3-lwjgl` inside `LwjglDisplay.createContext()` if it is wrong when running in full-screen and just print a log warn instead of throwing an exception.

**Comment by Ali-RS** [comment] 2023-01-09 14:34
Yet another solution is to do something like @riccardobl did with JmeDialogsFactory and JmeDialogsFactoryImpl. We need to create an interface `DisplayModesLoader` and provide the implementation in jme3-lwjgl module. AWTSettingsDialog class then will first need to look on the classpath for a `DisplayModesLoaderImpl` and if it found one it will use it if no implementation is found then will fall back to using AWT GraphicsEnvironment.

**Comment by stephengold** [comment] 2023-01-09 18:58
> we might get from one hole to another!

Based on my experience, if `org.lwjgl.opengl.Display.getAvailableDisplayModes()` puts us in a hole, it will be a *much* shallower hole than the one AWT has put us in.

LWJGL and AWT do not play nicely together.

**Comment by Ali-RS** [comment] 2023-01-09 19:27
I submitted a shallow fix in https://github.com/jMonkeyEngine/jmonkeyengine/pull/1898

It just gets rid of the exception to let the app continue running. For a proper solution, I will let someone else manage that.

**Comment by stephengold** [comment] 2023-01-10 06:31
> Yet another solution is to do something like riccardobl did with JmeDialogsFactory and JmeDialogsFactoryImpl.

I would be okay with that.

**Comment by Ali-RS** [comment] 2023-01-10 07:16
>I would be okay with that.

Care to design the interface in question?

**Comment by stephengold** [comment] 2023-01-10 18:00
> Are you willing to prototype the interface in question?

I'd rather not. Designing Java interfaces is not my strength, and I have many other tasks in my queue.

**Closed** 2023-01-11 05:58 UTC
Labels: bug
