### ISSUE TITLE
CollideIgnoreTransformTest.testPhantomTriangles: NPE

### ISSUE THREAD

**Issue by kruchinin-pavel** [jMonkeyEngine/jmonkeyengine#749] opened 2017-09-30 04:33 UTC
Fix is attached. I wished i would fix it directly, but too amateur for this repo to work.
[CollideIgnoreTransformTest.NPE.fix.patch.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/1346117/CollideIgnoreTransformTest.NPE.fix.patch.zip)

**Comment by stephengold** [comment] 2017-09-30 05:26
I'm OK with this change, and am available to integrate it, once wiser heads have reviewed it.

**Comment by Nehon** [comment] 2017-09-30 07:41
looks fine

**Comment by stephengold** [comment] 2017-10-01 07:25
Fixed in 'master' branch by pull request #750 (commit hash 94e828f).

@kruchinin-pavel please indicate whether or not the issue is resolved to your satisfaction.

**Comment by stephengold** [comment] 2017-11-07 17:55
Since the user who opened the issue has been unresponsive, mark this as closed.

**Closed by stephengold** 2017-11-07 17:55 UTC
