### ISSUE TITLE
fullscreen mode in LWJGL2 on Linux crashes during startup

### ISSUE THREAD

**Issue by RossComputerGuy** [jMonkeyEngine/jmonkeyengine#947] opened 2018-11-04 00:50 UTC
I get this exception while trying to put my game into any fullscreen resolution. Is there any way to go into fullscreen from the dialog that doesn't have this problem?
```
java.lang.RuntimeException: Unable to find fullscreen display mode matching settings
	at com.jme3.system.lwjgl.LwjglDisplay.createContext(LwjglDisplay.java:79)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:113)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:211)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stephengold** [comment] 2018-11-04 09:07
This appears to be a troubleshooting question. Such questions are best answered at the Forum:
    https://hub.jmonkeyengine.org/

**Comment by MeFisto94** [comment] 2018-11-04 18:14
I guess Linux and lwjgl3?
Then it's something we should really take care of. The Clue was that the settings dialog is falsely setting the frequency (setFrequency) as it's somehow differently reported by AWT/whatever we use to get the resolutions

**Comment by Ev1lbl0w** [comment] 2018-12-30 12:49
I had this problem too some time ago and reported it [here](https://hub.jmonkeyengine.org/t/error-cant-launch-jme3-projects-in-fullscreen/39625). It has not yet been fixed AFAIK but for anyone willing to dig deeper, here's what I found out:
- As @MeFisto94 said, this problem happens because LWJGL and AWT are reporting different refresh rates for the same resolution. Forcing the refresh rate to 60Hz in my case makes jMonkey apps able to go fullscreen.
- This problem is happening with the nvidia proprietary driver for linux, in my case. Switching to `nouveau` fixed these problems to me, so I encourage other people to test this as well. Back then I had a legacy driver (340.X), but even with the latest driver (415.X) this problem persists.

**Comment by louhy** [comment] 2019-06-01 18:32
I see these strange refresh rates coming from AWT too. Linux, NVidia proprietary drivers. I don't know if there's a fix, maybe a workaround, but that workaround (ex. force 60Hz on Linux) may just create a problem for someone else, no?

**Comment by riccardobl** [comment] 2019-06-02 07:56
If this happens on linux with lwjgl2, it might be related to this https://hub.jmonkeyengine.org/t/fix-for-unable-to-find-fullscreen-display-mode-matching-settings-for-multimonitor-configurations-in-linux/41510 .
LWJGL2 is unmaintained so i don't think we will get an official patch.

**Comment by louhy** [comment] 2019-06-02 09:44
Does anyone even use 2 anymore? I noticed a two year old comment from shadowislord about looking forward to removing it once 3 is stable, or something along those lines.

Also I'm pretty sure I was using 3 and seeing this issue. Isn't the issue related to AWT (or AWT interaction with NVidia drivers), though?

**Comment by riccardobl** [comment] 2019-06-02 09:47
I use 2. It's a generic error, it might be caused by several things.

**Comment by stephengold** [comment] 2019-06-02 16:14
I've encountered this issue on Linux Mint. Substituting the `jme3-lwjgl3` library for `jme3-lwjgl` works around the issue.

**Comment by louhy** [comment] 2019-06-02 18:33
Yeah, confirmed (also Linux Mint). 
To be clear, I still see the strange Hz options in the settings dialog, but instead of crashing, it just works. 
I guess can't be fixed and probably not worth it anyway.

**Comment by stephengold** [comment] 2019-06-02 19:47
> Does anyone even use 2 anymore?

LWJGL2 is still used by default in `jme3-examples` and the SDK. Also, Issue #942 might discourage some people from upgrading to LWJGL3.

**Comment by louhy** [comment] 2019-06-02 19:52
Yeah, I wasn't suggesting removal of 2 unless the answer was "nope", and clearly it's not.

**Comment by TriplexRoss** [comment] 2019-06-02 20:27
I use jme3

**Comment by louhy** [comment] 2019-06-02 21:24
> I use jme3

We all do :) This is about LWJGL2/3, a dependency which lets JME3 talk to OpenGL. 
Or do you actually mean lwjgl3?

**Comment by TriplexRoss** [comment] 2019-06-03 04:09
I actually mean lwjgl3

**Comment by louhy** [comment] 2019-06-03 04:26
Hmm. I definitely saw it go away when I switched to 3. Then this may be more complicated than it seems. :thinking:

**Comment by grizeldi** [comment] 2019-06-03 06:54
We had to write a custom launcher window for Lightspeed Frontier because of this, but afaik asking lwjgl directly worked, while whatever jme does internally did not.

**Comment by ertugrulcetin** [comment] 2020-12-03 18:04
I found this solution and it worked for me on OS X - MacBook Pro;

``` java
public static void main(String[] args) {
        GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();

        AppSettings setting = new AppSettings(true);
        setting.setFullscreen(true);
        setting.setFrameRate(60);
        setting.setFrequency(device.getDisplayMode().getRefreshRate());

        HelloTerrain app = new HelloTerrain();
        app.setShowSettings(false);
        app.setSettings(setting);
        app.start();
    }
```

**Comment by Ali-RS** [comment] 2023-01-04 05:52
>LWJGL2 is unmaintained so i don't think we will get an official patch.

Probably we should ship our own fork of LWJGL2.

**Comment by Ali-RS** [comment] 2023-01-11 06:05
Fixed in https://github.com/jMonkeyEngine/jmonkeyengine/commit/3e1b823bdb7c7a2e60916dab32186141b3fd9800 & https://github.com/jMonkeyEngine/jmonkeyengine/commit/4e80c9bc6891ee3c0ca54e707c165bb3a332fe41

**Closed by Ali-RS** 2023-01-11 06:05 UTC
Labels: bug, Contribution welcome
