### ISSUE TITLE
SDK SceneComposer Won't Open - OpenGL context not started! (Ubuntu 18.04 LTS)

### ISSUE THREAD

**Issue by ItsSeaJay** [jMonkeyEngine/jmonkeyengine#1131] opened 2019-06-25 17:29 UTC
When I try to edit a `.j3o` file in the SceneComposer using JMonkeyEngine SDK, nothing happens. Instead, I get the following error as a pop up in the bottom right of the window:

```
OpenGL context not started!

Click here to go to the troubleshooting web page.
```

This happens no matter what file I try to open through the editor. It only seems to happen on Ubuntu 18.04 LTS for me. I haven't encountered this issue on any of my other computers which all run Windows 10.

I'm using a Ryzen 5 2600 CPU and Radeon RX580 GPU, which is running on the latest 3rd-party drivers available for my system.

It should be noted that other 3D applications work fine, including the one I'm writing within the SDK itself. Just not the SceneComposer for whatever reason.

**Comment by pspeed42** [comment] 2019-06-25 21:14
Note: You are more likely to get help for trouble-shooting problems on the forum.

**Comment by stephengold** [comment] 2019-06-25 22:56
https://hub.jmonkeyengine.org/

**Comment by MeFisto94** [comment] 2020-02-16 20:33
Closing this as SDK issues are tracked at https://github.com/jMonkeyEngine/sdk and this is "no" issue but a troubleshooting problem, we'd first need to debug the cause to be able to report a specific issue.

**Closed by MeFisto94** 2020-02-16 20:33 UTC
Labels: [DEPRECATED]: SDK
