### ISSUE TITLE
Android sound is broken

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1239] opened 2019-12-31 10:24 UTC
It seems playing sound on Android has stopped working since we have updated the build script to build Android OpenAL natives by CI (since v3.3.0-alpha5).

Forum post:
https://hub.jmonkeyengine.org/t/sound-not-working-on-android-for-version-3-3-0-alpha5/42645/16

Unless someone is willing to go through the pain of debugging the issue on the native side we probably better revert the build script to use the good old precompiled OpenAL natives (which we were using in pre 3.3.0-alpha5 releases) instead of rebuilding them by CI.

**Comment by pspeed42** [comment] 2019-12-31 10:26
I concur.  I'm also willing to cut a beta2 at any point we are sure we've resolved some of the more immediate issues we've found this past week.

**Comment by Ali-RS** [comment] 2020-05-05 20:56
Yet another report
https://hub.jmonkeyengine.org/t/android-ogg-524/43233

**Comment by Ali-RS** [comment] 2020-05-06 12:40
Putting the workaround here so I won't repeat myself in possibly upcoming reports on the forum: 

> For now, one needs to use the 3.3.0-alpha-2 version for `jme3-android-native.jar`. 
Note that you can yet use JME 3.3.0-stable and higher for other jars and you should be fine.

**Comment by Ali-RS** [comment] 2020-11-10 19:29
Need to check if commit https://github.com/jMonkeyEngine/jmonkeyengine/commit/38a225cf8e766685ab090948033a0b3a0f822a25 is affecting this issue.

**Comment by MeFisto94** [comment] 2020-11-11 11:03
It should not, it shouldn't change anything in the bytecode at all. Also note I did a followup commit as it was broken.
It is something we should resolve and debugging that will be funny, helpful but also take a long time, so I'm more seeing that for 3.5 or at least not immediate as part of 3.4 as we've got a lot of other things ahead.

The ogg error seems to be unrelated but also interesting

**Comment by Ali-RS** [comment] 2020-11-18 14:02
>  take a long time, so I'm more seeing that for 3.5 or...

Could be 5 or more years...!!

I mean until then we can just revert it back to the good old prebuilt natives instead of shipping a broken API... :)

**Comment by stephengold** [comment] 2021-03-07 20:57
I looked into this. I don't believe we *ever* used pre-built natives in jme3-android-native. The most relevant change between 3.3.0-alpha5 and 3.3.0-beta1 was that the Android native build was moved from Travis to GitHub. Am I missing something?

**Comment by Ali-RS** [comment] 2021-03-08 05:13
The changes are made in 3.3.0-alpha3 https://github.com/jMonkeyEngine/jmonkeyengine/commit/90d3b69bd10c03d77b32e1877b6da478d4000b43

**Comment by stephengold** [comment] 2021-03-08 14:56
Those 3 files were auto-generated headers which should never have been committed in the first place, as was mentioned in  jme3-android-native/.gitignore . I don't understand how removing them caused exceptions to be thrown at runtime.

**Comment by stephengold** [comment] 2021-03-09 17:47
Thanks for investigating, @joliver82. I think this is an OK time to update openal-soft.

**Comment by joliver82** [comment] 2021-03-09 18:11
After some more testing I found that ogg issue is more or less the same, the call to ov_pcm_total ( https://github.com/jMonkeyEngine/jmonkeyengine/blob/fc8128c139ac6cbde7a8a8db665bb4e1ca6ecbc9/jme3-android-native/src/native/jme_decode/com_jme3_audio_plugins_NativeVorbisFile.c#L210 ) returns negative value. If setting -O0 the issue is fixed not sure why. So if that suits you, I'll change both mk files to add -O0 to fix the issue.

In fact, my intention is to create a PR including this and a newer release of openal-soft this week. 

Also, how do you think prebuilt natives should be stored? Nowadays, if buildNativeProjects = false is set, gradle downloads natives from https://dl.bintray.com/jmonkeyengine/files/${natives.snapshot}/jme3-natives.zip and uses them. As you know bintray will be shuted down in the near future so, if we want to keep prebuilt natives we need to store them in other place either git itself or any other repository

**Comment by stephengold** [comment] 2021-03-09 18:43
> I'll change both mk files to add -O0 to fix the issue.

For issue #1135, replacing `-Ofast` with `-O3` was sufficient. Have you tried with `-O3`?

> how do you think prebuilt natives should be stored?

Re issue #1468, we should switch to caching native builds at  https://objects.jmonkeyengine.org/native-snapshots

**Comment by joliver82** [comment] 2021-03-09 18:47
I've tried all -O options. For openal -O0 and -O1 worked. For decode only -O0 :(

**Comment by Ali-RS** [comment] 2021-03-10 05:27
@joliver82 thanks for the investigation and submiting a fix :)

**Comment by stephengold** [comment] 2021-03-13 22:12
Should be fixed in "master" branch at 8c4d523

**Closed by stephengold** 2021-03-13 22:13 UTC
Labels: Android, bug, buildscript
