### ISSUE TITLE
RawInput's onKeyEvent behaves differently on LWJGL 2 vs LWJGL 3

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#1083] opened 2019-05-02 18:58 UTC
LWJGL 3 seems to give more key events than LWJGL 2.

Simple state extending RawInputListener:
```
    @Override
    public void onKeyEvent(KeyInputEvent evt) {
        evt.toString();
    }
```

**Outcome**:
LWJGL3:
Key(CODE=31, PRESSED)
Key(CODE=0, CHAR=s, PRESSED)
Key(CODE=0, CHAR=s, RELEASED)

LWJGL2:
Key(CODE=31, CHAR=s, PRESSED)
Key(CODE=31, RELEASED)

If you compare the code, seems that the LWJGL 3 has 2 different listeners for the keys:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/989fc0a9f0dc7a5c46b6c5d1f479064cffda8023/jme3-lwjgl/src/main/java/com/jme3/input/lwjgl/LwjglKeyInput.java (LWJGL 2)
https://github.com/jMonkeyEngine/jmonkeyengine/blob/989fc0a9f0dc7a5c46b6c5d1f479064cffda8023/jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java (LWLGL 3)

I don't know if this is related:
https://github.com/jMonkeyEngine/jmonkeyengine/issues/942

**Comment by tonihele** [comment] 2019-05-02 19:27
Yeah... I'm not sure that does this deserve to be called a bug. Behavior is changed for sure and that is bad. But it seems that there is no easy way to unify the behavior...

**Comment by pspeed42** [comment] 2019-05-02 19:35
Yeah, unfortunately, input on lwjgl3 is a real mess with no good solutions.

**Comment by MeFisto94** [comment] 2019-08-09 11:21
Duplicate of #942 but containing some good information as well

**Closed by MeFisto94** 2019-08-09 11:21 UTC
