### ISSUE TITLE
Delete key not recognized

### ISSUE THREAD

**Issue by IamKayrox** [jMonkeyEngine/jmonkeyengine#960] opened 2018-11-23 16:07 UTC
The engine fails to recognize the delete key, also, documentation lacks any information on how the engine exactly maps the keys

**Comment by stephengold** [comment] 2018-11-23 19:13
The Del key should trigger key input events with the code `KeyInput.KEY_DELETE` = 211. At least it does in a Microsoft Windows environment with US layout using JME v3.2.1 with LWJGL v2.9.3 .

If that doesn't work for you, we'll need more information about the environment where you encountered this issue, such as its operating system, keyboard layout, and which version of JME/LWJGL you used. A short, self-contained example might also help.

**Comment by IamKayrox** [comment] 2018-11-23 22:08
I'm using Windows 10 v1803 with international Spanish layout, I'm using the last version of IntelliJ idea and the project is seted up with gradle

**Comment by stephengold** [comment] 2018-11-23 22:35
There's a known issue #942 triggered by using LWJGL v3.1.6 with a non-US keyboard layout.

The LWJGL version number should be logged to the console when your application starts, like so:
```
INFO: LWJGL 3.1.6 build 14 context running on thread main
```

Please retry your test with LWJGL v2.9.3 . This will probably involve replacing `jme3-lwjgl3` with `jme3-lwjgl` in your build script.

**Comment by stephengold** [comment] 2018-11-26 16:54
Lacking the results of the retry, I will close this issue as a duplicate of #942. Reopen if there's more to discuss.

**Closed by stephengold** 2018-11-26 16:54 UTC
Labels: duplicate
