### ISSUE TITLE
BatchNode

### ISSUE THREAD

**Issue by zzuegg** [jMonkeyEngine/jmonkeyengine#189] opened 2014-11-25 16:42 UTC
BatchNode ignores scale of parent if not moved. 
https://gist.github.com/zzuegg/f916072dc4242a88acfd
Tested against stable

**Comment by shadowislord** [comment] 2015-01-31 21:24
Cannot reproduce in 3.1. Closing.

**Closed by shadowislord** 2015-01-31 21:24 UTC
Labels: bug
