### ISSUE TITLE
MTLLoader fails to recognize relative path

### ISSUE THREAD

**Issue by NetzwergX** [jMonkeyEngine/jmonkeyengine#959] opened 2018-11-23 14:25 UTC
Loading an `.obj` file with an `.mtl` file fails if the material specifies the texture location with absolute or relative paths.

I have these lines in my `.mtl` file:

    map_Ka Textures\\K_BuildingsA_01.jpg
    map_Kd Textures\\K_BuildingsA_01.jpg

This should load the files properly from the subdirectory, but does not due to 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/53c788c031df04ac6ac4ff34b2029026e7348e1e/jme3-core/src/plugins/java/com/jme3/scene/plugins/OBJLoader.java#L333

While I understand why you included this workaround - a lot of people aren't able to properly export their models - and the cludge that seems to fix that in most situations, its simply breaking all models that are properly exported with relative paths, especially when using a pipeline that includes 3rd party 3D modeling applications.

**Comment by stephengold** [comment] 2018-11-26 17:11
Perhaps we need an option to switch between (a) the workaround and (b) support for pathnames. Could be as simple as a boolean flag in the asset key.

**Comment by pspeed42** [comment] 2018-11-26 22:10
We support relative paths in other loaders... not sure why we don't in this one.  Absolute paths is typically a hard-veto.  Whenever possible we try to avoid having to answer forum questions about "My game runs on my machine but nowhere else" style questions that have to do with path mistakes.  Absolute paths won't work in a packaged game and so JME won't support them.

**Comment by NetzwergX** [comment] 2018-11-29 15:14
@pspeed42 Absolutely agreed. But relative paths should work. Currently, the MTLLoader is limited to having textures in the same directory as the `.obj` file - which is very limiting. Most 3D modeling programs have an option for OBJ files to switch from absolute to relative paths, precisely in order to enable reuse. When using 3rd party assets (not made with the SDK, e.g. bought ones or ones made with another program), one would expect JME3 to being able to properly read them.

**Comment by stephengold** [comment] 2018-12-16 00:57
I believe this is a duplicate of issue #96.

**Comment by stephengold** [comment] 2019-01-08 16:51
Closed as a duplicate.

**Closed by stephengold** 2019-01-08 16:51 UTC
Labels: duplicate
