### ISSUE TITLE
Shadows don't work on CompareMode.Hardware

### ISSUE THREAD

**Issue by Bebul** [jMonkeyEngine/jmonkeyengine#271] opened 2015-05-07 08:43 UTC
It seems, the whole scene is in shadow in the current jME version.
I have tried to track the relevant commit and it is like this:
Shadows bad: ed4b70bcad5052ff76b509a3f39e1647102115c7
Shadows ok: 389b117fb64388724f9e25a18bac3ff8ee008fae
( by @shadowislord )

The following screenshot showing the problem are from jME test *TestDirectionalLightShadow.java*
![image](https://cloud.githubusercontent.com/assets/9265147/7511474/5a64c2a8-f4a5-11e4-8f71-3dc2e0f1b535.png)
While it should look like this:
![image](https://cloud.githubusercontent.com/assets/9265147/7511519/a34dc67c-f4a5-11e4-99f1-ff3f7e5529c3.png)

**Comment by Nehon** [comment] 2015-07-04 16:59
Can't reproduce the issue.
Could you give some details on your hardware?

**Comment by Bebul** [comment] 2015-07-07 12:07
> Can't reproduce the issue.
I have tried two things at the moment:
  1. take fe057130a4d432f0e153fac3b7d28e42c07dda69 again and debug testDirectionalLightShadow.java again. **Shadows were still bad!**
  2. take the latest 6d1ab7af6590f3654f5349367ad2e87ed1162709 and debug testDirectionalLightShadow.java. **Shadows working!**

> Could you give some details on your hardware?
Seems strange that it works now but not during some range of revisions. But it is no longer issue for me now, as it works in actual rev.
I have notebook with: NVidia GeForce GT 555M (driver completely reinstalled when this issue noticed on start of May, 2015).

**Comment by Nehon** [comment] 2015-07-07 12:10
Alright, I guess a following commit fixed the issue.
Good.
Closing this issue. Thanks

**Closed by Nehon** 2015-07-07 12:10 UTC
