### ISSUE TITLE
HelloCollision gravity inverted

### ISSUE THREAD

**Issue by w1lford** [jMonkeyEngine/jmonkeyengine#1034] opened 2019-03-07 21:21 UTC
I ran the exact example code for HelloCollision.java and while the gravity works, it is inverted and causes the player to fall upward into the sky. 
I am using jMonkeyEngine v 3.2.2-stable-sdk1 Linux 64 bit.

**Comment by pspeed42** [comment] 2019-03-07 21:23
Ask questions like this on the forum.  I believe this was discussed recently.  You may find it in a search.

**Comment by w1lford** [comment] 2019-03-07 21:31
How would this not be an issue with the code itself when I run the exact example code? Shouldn't the example be fixed so that it works for people in the future?

**Comment by pspeed42** [comment] 2019-03-07 21:32
You didn't post a bug.  You asked a question.... that no one but maybe three people will ever read.

It's an easy fix on our end... just delete the example.

**Comment by w1lford** [comment] 2019-03-07 21:34
The example is used in Jmonkey's documentation. Are you going to delete that as well? Why use example code in the documentation that doesn't work?

**Comment by pspeed42** [comment] 2019-03-07 21:37
This is an unproductive line of questioning.  There is actually an approach that IS productive:
1) ask the question on the forum or search for the existing question to see if it's a legitimate problem, a setup problem, etc.
2) find out the bunch of things you left out of a proper bug report such as what version you were running, which bullet you were running, etc..
3) potentially have gained enough knowledge to point out what is actually wrong with the example so someone can fix it... but even if not, you won't be sending anyone on a wild goose chase asking forum questions in a problem report.

**Comment by w1lford** [comment] 2019-03-07 21:39
Or if someone proofread the documentation for JMonkeyEngine this bug wouldn't have to be opened in the first place.

**Comment by pspeed42** [comment] 2019-03-07 21:40
Guess what?  That someone is you!!!!  And everyone else.  Then you too can bask in the fame and fortune of being a "jme dev"... or you will realize that this is all volunteer and supported by the community.

But I'll tell you what, I'll reopen this issue and just let the question stand: "Does anyone else have this issue when they run this code?"

Where "anyone" is probably two people.

**Comment by w1lford** [comment] 2019-03-07 21:42
This is easy to test. All you have to do is download the code and run it. I've already done that. Maybe you could do that too and we can try to fix this bug together.

**Comment by pspeed42** [comment] 2019-03-07 21:45
Or you could look on the forum and ask on the forum and "together" could be hundreds of people instead of two people... one of whom has no time at all to fix documentation and happens to be doing "data entry style coding" for "day job" right now or else I wouldn't even be trying to help you actually resolve your issue here.

**Comment by riccardobl** [comment] 2019-03-07 21:48
Might be related to this https://github.com/jMonkeyEngine/jmonkeyengine/issues/910

**Comment by w1lford** [comment] 2019-03-07 21:51
Then why are you on Github at all if you're at your job? Isn't that what you're being paid to do? If you don't have time to actually contribute then why post anything at all? Leave the issue up for other people who have time to look at.

**Comment by pspeed42** [comment] 2019-03-07 21:52
Which is why "which bullet?" is an important question to ask.

Personally, I get tired of playing the game of "20 questions" with every new bug report that consists of nothing more than "Hey, X is broken."  After the 5000th time it got a little old.  So I direct folks to the forum where newer users have only done that 1000 times and might still be willing to play 20 questions.

Obviously this code worked once for someone.  So something regressed.  Or something is specific about how it's being run.

In case, at some point it could turn into a proper bug with the details necessary to fix it.  Because I'm 90% sure that if I tried this code it would work for me.

**Comment by pspeed42** [comment] 2019-03-07 21:53
re: " If you don't have time to actually contribute then why post anything at all?"

I AM contributing.  I'm trying to tell you how to get the help you need.  It's like your standing in the wrong line at the DMV and I'm telling you the right line... and your just arguing "Why can't I be helped in this line?"   Well, you haven't filled out the right forms for one.

**Comment by w1lford** [comment] 2019-03-07 21:58
I'm not going to continue down this road. The only thing I'll say is that you shouldn't just close an issue 3 seconds after it's been made because it doesn't fit your idea of a proper bug report. The end goal here should be improving this engine in any way it can be.

**Comment by pspeed42** [comment] 2019-03-07 22:01
I opened it again... so you can check back in a few years when it's still sitting here because no one wants to touch it.  It lacks any useful information.  But I'll leave it open.

If you decide you care more about actually solving the problem than getting into pissing matches with people who are trying to help you then you can try a more productive approach.

Probably you will get lucky and someone else will also discover this bug and provide the fix and/or proper details so someone doesn't waste their valuable free time chasing down bad leads.

**Comment by w1lford** [comment] 2019-03-07 22:21
I just tried running on v3.2.2-stable-sdk1 on Mac OS X and I get the same issue.

**Comment by stephengold** [comment] 2019-03-07 22:48
This is a duplicate of issue #910.

**Closed** 2019-03-07 22:50 UTC
Labels: duplicate
