### ISSUE TITLE
TestPBRLighting crashes with an invalid enum error when assertions are enabled.

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#374] opened 2015-11-05 22:05 UTC
Enable assertion, launch TestPBRLighting, you got it.
invalid enum on a glCheckError.
Works fine otherwise, but still...

**Comment by shadowislord** [comment] 2015-11-06 01:57
Closing due to lack of information / stack trace / etc.

**Comment by Nehon** [comment] 2015-11-06 06:17
Dude... that's just a remainder for me to fix it... You don't need information...

**Comment by shadowislord** [comment] 2017-09-15 02:32
Still no information about the issue. I am guessing this is a duplicate of #558 which is also an "invalid enum" error.

**Closed by shadowislord** 2017-09-15 02:32 UTC
