### ISSUE TITLE
still have this problem about error #490

### ISSUE THREAD

**Issue by GitHub-Ronald** [jMonkeyEngine/jmonkeyengine#1091] opened 2019-05-21 09:07 UTC
com.jogamp.opengl.GLException: jME3 Main: No OpenGL context current on this thread.
at com.jme3.system.jogl.JoglContext.determineMaxSamples(JoglContext.java:347).
please help!

**Comment by stephengold** [comment] 2019-06-19 18:06
Duplicate of issue #490. Follow-up to that issue.

**Closed by stephengold** 2019-06-19 18:06 UTC
