### ISSUE TITLE
Using Nifty GUI in jME 3.1 prevents the application from closing

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#330] opened 2015-09-04 18:52 UTC
Cross referencing this from the Nifty GUI issue tracker:
https://github.com/void256/nifty-gui/issues/365

Seems to happen due to some timer threads (Timer-0, etc) staying alive even after all other user threads have exited.

**Comment by Mordag** [comment] 2015-11-08 14:57
Current status can be found here: https://github.com/void256/nifty-gui/issues/364 Seems like that's not going to be fixed anytime soon.

**Comment by Mordag** [comment] 2016-02-18 01:29
It seems like it's not a problem related to nifty. According to the tracker (https://github.com/nifty-gui/nifty-gui/issues/364) it has something to do with jmonkey.

**Comment by tonihele** [comment] 2016-03-13 16:10
It is their subscriber, not JME I think. I updated my findings there.

**Comment by bgroenks96** [comment] 2016-04-03 18:45
The problem was with the archaic EventBus library that Nifty 1.4.x uses. void256 merged the EventBus library into the Nifty source tree and fixed the bug.

To fix this issue:

1. Get the latest snapshot of Nifty 1.4.2 from [this repository](https://oss.sonatype.org/content/repositories/snapshots/com/github/nifty-gui/nifty/1.4.2-SNAPSHOT/)
2. **Delete the EventBus JAR** from your maven cache or libs folder. This is really important!
3. Tell Maven, Gradle, Ant, etc whatever you're using to use the latest version of Nifty from the repo mentioned above. The EventBus classes (along with patch) are now packaged in the Nifty JAR.

After that, the problem should be resolved. If you encounter any further issues, please let us know [here](nifty-gui/nifty-gui#364).

**Comment by tonihele** [comment] 2017-03-18 23:50
This can be closed? The issue is fixed already. JME 3.1 carries 1.4.2 release which has the issue fixed.

**Comment by stephengold** [comment] 2018-01-17 19:00
I believe this can be closed.

**Closed** 2018-01-17 21:57 UTC
Labels: Contribution welcome, bug
