### ISSUE TITLE
UnsatisfiedLinkError: libjawt.so: version `SUNWprivate_1.1' not found (lwjgl2)

### ISSUE THREAD

**Issue by vushu** [jMonkeyEngine/jmonkeyengine#1215] opened 2019-11-14 23:04 UTC
when trying to run using java 13 this error occurs:
```
INFO: Running on jMonkeyEngine 3.3-alpha5
 * Branch: HEAD
 * Git Hash: bb32b88
 * Build Date: 2019-09-25
Exception in thread "jME3 Main" java.lang.UnsatisfiedLinkError: /home/vushu/coding/java/jmonkey/magicman/liblwjgl64.so: /home/vushu/.sdkman/candidates/java/13.0.1-open/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /home/vushu/coding/java/jmonkey/magicman/liblwjgl64.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2440)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2497)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:744)
        at java.base/java.lang.System.load(System.java:1873)
        at org.lwjgl.Sys$1.run(Sys.java:70)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:87)
        at org.lwjgl.Sys.<clinit>(Sys.java:117)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:210)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by vushu** [comment] 2019-11-15 09:51
a work around is to use 13.0.1-zulu instead of open the java 13 openjdk

**Comment by stephengold** [comment] 2019-11-17 20:52
Does it also occur with earlier JDKs, such as java11 JDKs?

**Comment by vushu** [comment] 2019-11-17 21:50
I just tested the earlier version and It works fine using openjdk 12 and 11

**Comment by Ali-RS** [comment] 2019-11-18 05:47
Have you also tried with LWJGL3?

**Comment by Ali-RS** [comment] 2019-12-01 08:38
Had a chance to test this with OpenJDK 13, using LWJGL 2 I am getting the same error but works fine with LWJGL 3. 

I am closing this as this seems to be an LWJGL 2 compatibility issue which is not actively maintained anymore.

**Comment by Ali-RS** [comment] 2023-01-04 16:42
I can confirm using the natives provided in https://github.com/libgdx/libgdx/commit/778c936c9cc35c20ded87c2ff95252c217831963 resolves this issue. 

It also seems to fix this issue https://github.com/jMonkeyEngine/jmonkeyengine/issues/1887 (I have never run into that issue before so I can not be 100% sure)

@MeFisto94 I noticed you have an updated fork of lwjgl2, are you willing to add these natives to your fork and ship it to maven (we can also migrate your fork to JME github and upload artifacts manually to maven using sonatype Staging Upload) and update JME to use it?

**Comment by stephengold** [comment] 2023-01-04 16:48
Oracle's Java SE 13 reached end of support in March 2020. Does the issue also occur with Java 17?

**Comment by Ali-RS** [comment] 2023-01-04 16:50
Yes, I can reproduce that issue with OpenJDK 17.

**Comment by Ali-RS** [comment] 2023-01-04 21:00
I found out the [2.9.4 version ](https://github.com/MeFisto94/lwjgl/releases/tag/refs%2Ftags%2F2.9.4) @MeFisto94  has released on his fork also does work fine with newer JDKs and I do not get `libjawt.so: version 'SUNWprivate_1.1' not found` error. This is great!

We now need to confirm if it also works fine against this issue https://github.com/jMonkeyEngine/jmonkeyengine/issues/1887
What OpenJDK version I should use to be able to reproduce the `Inconsistency detected by ld.so: dl-lookup.c: 111` ?

**Comment by MeFisto94** [comment] 2023-01-05 15:59
This should be #1247 as well (i.e. the missing version just crashed at the assertion on older versions instead of showing this nice error).

> @MeFisto94 I noticed you have an updated fork of lwjgl2, are you willing to add these natives to your fork and ship it to maven (we can also migrate your fork to JME github and upload artifacts manually to maven using sonatype Staging Upload) and update JME to use it?

Tbh I was not even aware I managed to build it properly, or I think I wasn't sure about the jars (never just replaced the natives), so it may need testing of all corner cases.
Either way, it should probably be hosted at the jme organization, so everyone could try to fix it (in case there are more problems).

**Comment by Ali-RS** [comment] 2023-01-11 05:56
Fixed in https://github.com/jMonkeyEngine/jmonkeyengine/commit/3e1b823bdb7c7a2e60916dab32186141b3fd9800

**Closed by Ali-RS** 2023-01-11 05:56 UTC
Labels: defect
